//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameNepal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int id { get; set; }
        public string filepath { get; set; }
        public string filename { get; set; }
        public string description { get; set; }
        public int displayorder { get; set; }
        public bool isActive { get; set; }
        public System.DateTime createdate { get; set; }
        public System.DateTime updatedate { get; set; }
    }
}
