//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameNepal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRate
    {
        public int id { get; set; }
        public int gameid { get; set; }
        public int gamecurrency { get; set; }
        public int value { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
    }
}
