//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameNepal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordToken
    {
        public int id { get; set; }
        public int userid { get; set; }
        public System.Guid token { get; set; }
        public System.DateTime createdate { get; set; }
        public bool isValid { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
    }
}
